name: "IFC schema check"

on:
  pull_request:
    branches:
      - master

jobs:
  filter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Filter only changed files
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ','
          fileOutput: ','
      - name: Logging
        run: |
          echo 'All files:'
          cat $HOME/files.csv ; echo
          echo 'Modified files:'
          cat $HOME/files_modified.csv ; echo
          echo 'Added files:'
          cat $HOME/files_added.csv ; echo
          echo 'Removed files:'
          cat $HOME/files_removed.csv ; echo
          echo 'Files: ' '${{ steps.file_changes.outputs.files}}'
          echo 'Modified: ''${{ steps.file_changes.outputs.files_modified}}'
          echo 'Added: ''${{ steps.file_changes.outputs.files_added}}'
          echo 'Removed: ''${{ steps.file_changes.outputs.files_removed}}'
      - name: Check for IFC changes
        id: check
        run: |
          if grep -q .ifc "${{ steps.file_changes.outputs.files}}"; then 
            echo ::set-output name=HASIFCS::true; 
          else 
            echo ::set-output name=HASIFCS::false; 
          fi
      - name: Upload all files list
        if: ${{ steps.output_file.outputs.HASIFCS }}
        uses: actions/upload-artifact@v2
        with:
          name: all.csv
          path: ${{ steps.file_changes.outputs.files}}
      - name: Upload added files list
        if: ${{ steps.output_file.outputs.HASIFCS }}
        uses: actions/upload-artifact@v2
        with:
          name: added.csv
          path: ${{ steps.file_changes.outputs.files_added}}
          if-no-files-found: ignore # 'warn' or 'error' are also available
      - name: Upload modified files list
        if: ${{ steps.output_file.outputs.HASIFCS }}
        uses: actions/upload-artifact@v2
        with:
          name: modified.csv
          path: ${{ steps.file_changes.outputs.files_modified}}
          if-no-files-found: ignore # 'warn' or 'error' are also available
  check:
    runs-on: windows-latest
    needs: [filter]
    steps:
      - name: Verify the workspace context
        run: echo 'Workspace directory is ${{ github.workspace }}'
      - name: Load added files from filter job
        uses: actions/download-artifact@v2
        with:
          name: added.csv
      - name: Load modified files from filter job
        uses: actions/download-artifact@v2
        with:
          name: modified.csv
      - name: Get KIT checker tool
        uses: engineerd/configurator@v0.0.5
        with:
          name: "ifcCheckingTool_Lite.exe"
          url: "https://bwsyncandshare.kit.edu/s/3morKMDHr6fciP5/download"
          pathInArchive: "IfcChecker_KIT/ifcCheckingTool_Lite.exe"
      - name: Testing help
        run: |
          ifcCheckingTool_Lite.exe /?

